spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 156437734
    username: root
    url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8
server:
  servlet:
    context-path: /bookcity3