server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    password: 156437734
    url: jdbc:mysql://47.98.210.55:3306/seata_order?serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
    global-config:
      db-config:
        logic-not-delete-value: 0
        logic-delete-value: 1
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

